[package]
name = "rosalind-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }  # For parsing CLI arguments
colored = "2"
num-bigint = "0.4"
num-traits = "0.2"
reqwest = { version = "0.11", features = ["blocking", "json"] }